apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.namespace }}'
  name: '{{ .Values.project_id }}-publisher-svc-{{ .Values.region }}'
  labels:
    app: publisher
spec:
  selector:
    app: publisher
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
