apiVersion: v1
data:
  EVENT_SUBSCRIPTION: '{{ .Values.config_maps.event_subscription }}'
  SUBSCRIBER_PARALLEL_PULL_COUNT: "1"
  SUBSCRIBER_FLOW_CONTROL_MAX_OUTSTANDING_MESSAGES: "100"
  SUBSCRIBER_THREADS: "4"
  METRICS_TOPIC: '{{ .Values.config_maps.metrics_topic }}'
  PUBLISHER_THREADS: "4"
  PUBLISHER_BATCH_SIZE: "100"
  
kind: ConfigMap
metadata:
  namespace: '{{ .Values.namespace }}'
  labels:
    app: subscriber
  name: '{{ .Values.project_id }}-subscriber-config-maps-{{ .Values.region }}'
